Update CODEOWNDERS
CircleCI-Public/circleci-runner-docker pull request #29
Opened 2023-06-26 13:50 UTC by Stuart133

2023-06-28 13:48 UTC, atulsingh0 requested changes

2023-06-29 11:28 UTC, Stuart133 commented on .github/CODEOWNERS
> +* @CircleCI-Public/on-prem
It seems the teams are case insensitive (hence the CODEOWNERS validation passing) so I'd rather leave this lower case

2023-06-29 11:30 UTC, atulsingh0 approved these changes

2023-06-29 11:31 UTC, christian-stephen approved these changes

2023-06-29 11:39 UTC, merged